"""
Hook lifecycle manager — install manifest and atomic install/uninstall API.

Every ClawMetry component that modifies a runtime config file or drops a hook
file on disk MUST go through this module so that ``clawmetry uninstall`` and
the macOS drag-to-trash watchdog can cleanly undo everything that was installed.

Usage (from a runtime-specific installer)::

    from clawmetry.hooks import HookSpec, install, uninstall, status, verify_all

    spec = HookSpec(
        id="claude_code.approval_prompt_capture",
        runtime="claude_code",
        purpose="capture approval prompt text for replay",
        install_path="~/.claude/hooks/clawmetry-approval-capture.js",
        hook_content="/* generated by ClawMetry */\\n",
        target_config="~/.claude/settings.json",
        target_config_key="hooks.PreToolUse",
        target_config_value=["~/.claude/hooks/clawmetry-approval-capture.js"],
    )
    install(spec)         # idempotent
    uninstall(spec.id)   # cleans up atomically
"""
from __future__ import annotations

import hashlib
import json
import os
import shutil
import tempfile
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, List, Optional

try:
    import fcntl as _fcntl
    _HAS_FCNTL = True
except ImportError:
    _HAS_FCNTL = False  # Windows; parallel-write guard is best-effort

__all__ = [
    "HookSpec",
    "HookStatus",
    "HookVerdict",
    "install",
    "uninstall",
    "uninstall_all",
    "status",
    "verify_all",
]

_MANIFEST_DIR  = Path("~/.clawmetry/hooks").expanduser()
_MANIFEST_PATH = _MANIFEST_DIR / "installed.json"
_BACKUP_DIR    = _MANIFEST_DIR / "backups"
_LOCK_PATH     = _MANIFEST_DIR / ".manifest.lock"


# ---------------------------------------------------------------------------
# Public types
# ---------------------------------------------------------------------------

@dataclass
class HookSpec:
    """Everything needed to install a single runtime hook."""

    id: str
    """Stable unique identifier, e.g. ``claude_code.approval_prompt_capture``."""

    runtime: str
    """Target runtime slug, e.g. ``claude_code``, ``openclaw``."""

    purpose: str
    """Human-readable one-liner describing what the hook captures."""

    install_path: str
    """Absolute (or ``~``-relative) path where the hook file will be written."""

    hook_content: str = ""
    """Text content to write at *install_path*."""

    target_config: Optional[str] = None
    """Runtime config file to patch, e.g. ``~/.claude/settings.json``."""

    target_config_key: Optional[str] = None
    """Dot-path key inside *target_config* to set, e.g. ``hooks.PreToolUse``."""

    target_config_value: Optional[Any] = None
    """JSON-serialisable value to write at *target_config_key*."""

    clawmetry_version: str = ""
    """ClawMetry version string recorded at install time."""


@dataclass
class HookStatus:
    """Live state of a single registered hook (returned by :func:`status`)."""

    id: str
    runtime: str
    purpose: str
    install_path: str
    installed_at: str
    clawmetry_version: str
    file_present: bool = False
    checksum_ok: bool = False
    config_present: bool = False


@dataclass
class HookVerdict:
    """Integrity check result for a single hook (returned by :func:`verify_all`)."""

    id: str
    ok: bool
    issues: List[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def install(spec: HookSpec) -> None:
    """Install *spec* atomically and register it in the manifest.

    Steps:

    1. Back up *target_config* (if provided).
    2. Write *hook_content* to *install_path* atomically (tmp-then-rename).
    3. Patch *target_config* at *target_config_key* with *target_config_value*.
    4. Append an entry to ``installed.json``.

    Idempotent: if *spec.id* is already registered, returns immediately.
    Raises :class:`RuntimeError` on any failure and rolls back partial changes.
    """
    _ensure_dirs()
    install_path = Path(spec.install_path).expanduser()
    backup_path: Optional[Path] = None

    with _ManifestLock():
        manifest = _load_manifest()
        if any(h["id"] == spec.id for h in manifest["hooks"]):
            return

        try:
            if spec.target_config:
                backup_path = _backup_file(spec.target_config)

            checksum = _write_atomic(install_path, spec.hook_content)

            if spec.target_config and spec.target_config_key is not None:
                _patch_json(
                    spec.target_config,
                    spec.target_config_key,
                    spec.target_config_value,
                )

        except Exception as exc:
            if install_path.exists():
                try:
                    install_path.unlink()
                except OSError:
                    pass
            raise RuntimeError(
                f"hook install failed for {spec.id!r}: {exc}"
            ) from exc

        manifest["hooks"].append({
            "id":                  spec.id,
            "runtime":             spec.runtime,
            "purpose":             spec.purpose,
            "install_path":        str(install_path),
            "target_config":       spec.target_config,
            "target_config_key":   spec.target_config_key,
            "backup_path":         str(backup_path) if backup_path else None,
            "checksum":            checksum,
            "installed_at":        _utcnow(),
            "clawmetry_version":   spec.clawmetry_version,
        })
        _save_manifest(manifest)


def uninstall(hook_id: str) -> None:
    """Remove the hook identified by *hook_id* and restore any backed-up config.

    No-op if *hook_id* is not in the manifest.
    """
    with _ManifestLock():
        manifest = _load_manifest()
        entry = next((h for h in manifest["hooks"] if h["id"] == hook_id), None)
        if entry is None:
            return
        _remove_entry(entry)
        manifest["hooks"] = [h for h in manifest["hooks"] if h["id"] != hook_id]
        _save_manifest(manifest)


def uninstall_all() -> List[str]:
    """Uninstall every registered hook. Returns the list of removed hook IDs.

    Intended for use by ``clawmetry uninstall`` and the drag-to-trash watchdog.
    """
    with _ManifestLock():
        manifest = _load_manifest()
        removed: List[str] = []
        for entry in list(manifest["hooks"]):
            _remove_entry(entry)
            removed.append(entry["id"])
        manifest["hooks"] = []
        _save_manifest(manifest)
    return removed


def status() -> List[HookStatus]:
    """Return the live status of every hook registered in the manifest."""
    manifest = _load_manifest()
    out: List[HookStatus] = []
    for h in manifest["hooks"]:
        path = Path(h["install_path"])
        file_present = path.exists()
        checksum_ok = False
        if file_present and h.get("checksum"):
            try:
                checksum_ok = _checksum(path.read_bytes()) == h["checksum"]
            except OSError:
                pass
        config_present = bool(
            h.get("target_config")
            and Path(h["target_config"]).expanduser().exists()
        )
        out.append(HookStatus(
            id=h["id"],
            runtime=h["runtime"],
            purpose=h["purpose"],
            install_path=h["install_path"],
            installed_at=h.get("installed_at", ""),
            clawmetry_version=h.get("clawmetry_version", ""),
            file_present=file_present,
            checksum_ok=checksum_ok,
            config_present=config_present,
        ))
    return out


def verify_all() -> List[HookVerdict]:
    """Check the integrity of every registered hook.

    Returns one :class:`HookVerdict` per hook. Hooks with ``ok=False`` should
    be reinstalled via ``install(spec)`` or deregistered via ``uninstall(id)``.
    Called by the daemon on start-up to self-heal after out-of-band changes.
    """
    verdicts: List[HookVerdict] = []
    for s in status():
        issues: List[str] = []
        if not s.file_present:
            issues.append("hook file missing from disk")
        elif not s.checksum_ok:
            issues.append("hook file modified or corrupted since install")
        verdicts.append(HookVerdict(id=s.id, ok=not issues, issues=issues))
    return verdicts


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------

def _ensure_dirs() -> None:
    _MANIFEST_DIR.mkdir(parents=True, exist_ok=True)
    _BACKUP_DIR.mkdir(parents=True, exist_ok=True)


def _utcnow() -> str:
    import datetime
    return datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")


def _checksum(data: bytes) -> str:
    return "sha256:" + hashlib.sha256(data).hexdigest()


def _write_atomic(path: Path, content: str) -> str:
    """Write *content* to *path* via tmp-then-rename. Returns a SHA-256 checksum."""
    path.parent.mkdir(parents=True, exist_ok=True)
    encoded = content.encode("utf-8")
    fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".clawmetry-tmp-")
    try:
        with os.fdopen(fd, "wb") as fh:
            fh.write(encoded)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    return _checksum(encoded)


def _backup_file(config_path: str) -> Optional[Path]:
    src = Path(config_path).expanduser()
    if not src.exists():
        return None
    stamp = time.strftime("%Y%m%dT%H%M%S")
    dst = _BACKUP_DIR / f"{src.name}_{stamp}.bak"
    shutil.copy2(src, dst)
    return dst


def _restore_file(config_path: str, backup_path: str) -> None:
    src = Path(backup_path)
    if not src.exists():
        return
    _write_atomic(Path(config_path).expanduser(), src.read_text(encoding="utf-8"))


def _patch_json(config_path: str, key: str, value: Any) -> None:
    """Set dot-path *key* to *value* in a JSON config file.

    Preserves all existing keys. The modified node gets a ``__clawmetry: true``
    sentinel so a future fine-grained merge-remove can identify our entries.
    """
    path = Path(config_path).expanduser()
    data: dict = {}
    if path.exists():
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            data = {}
    parts = key.split(".")
    node = data
    for part in parts[:-1]:
        node = node.setdefault(part, {})
    node[parts[-1]] = value
    node.setdefault("__clawmetry", True)
    _write_atomic(path, json.dumps(data, indent=2))


def _remove_entry(entry: dict) -> None:
    """Remove a hook's file and restore its config backup (best-effort)."""
    if entry.get("backup_path") and entry.get("target_config"):
        try:
            _restore_file(entry["target_config"], entry["backup_path"])
        except Exception:
            pass
    install_path = Path(entry["install_path"])
    if install_path.exists():
        try:
            install_path.unlink()
        except OSError:
            pass


class _ManifestLock:
    """Exclusive file lock on the manifest for concurrent-daemon safety (Unix only)."""

    def __enter__(self) -> "_ManifestLock":
        _ensure_dirs()
        self._fh = open(_LOCK_PATH, "w")
        if _HAS_FCNTL:
            _fcntl.flock(self._fh, _fcntl.LOCK_EX)
        return self

    def __exit__(self, *_: Any) -> None:
        if _HAS_FCNTL:
            _fcntl.flock(self._fh, _fcntl.LOCK_UN)
        self._fh.close()


def _load_manifest() -> dict:
    if not _MANIFEST_PATH.exists():
        return {"hooks": []}
    try:
        return json.loads(_MANIFEST_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {"hooks": []}


def _save_manifest(manifest: dict) -> None:
    _ensure_dirs()
    _write_atomic(_MANIFEST_PATH, json.dumps(manifest, indent=2))
