"""Tell what a human typed apart from context a harness injects as a user turn.

Several runtimes write setup context into the ``user`` role, so "the first user
message" is often not the person at all (founder report 2026-09-11: every Codex
session was titled "# AGENTS.md instructions for /Users/…", its replay opened on
a "YOU" bubble holding the repo's AGENTS.md, and the real "hello" was turn 2).
Verified shapes, one runtime each:

* Codex: ``# AGENTS.md instructions for <cwd>`` + ``<INSTRUCTIONS>`` and
  ``<environment_context>`` blocks; ``<recommended_plugins>``,
  ``<in-app-browser-context>``; the prompt wrapped as
  ``# Files mentioned by the user: … ## My request:`` (attachments),
  ``# Context from my IDE setup: … ## My request for Codex:`` (IDE) and
  ``<realtime_delegation> <input>…</input>`` (voice).
* Cursor agent: ``<timestamp>…</timestamp> <user_query>…</user_query>``.
* Cline: ``<task>…</task>`` then ``<environment_details>``.
* Claude Code / Qwen Code: ``<system-reminder>``, ``<task-notification>``,
  ``<local-command-stdout>``, the ``Caveat:`` resume preamble, the
  "This session is being continued…" compaction summary,
  ``[Request interrupted by user]`` and ``[Image: source: <path>]`` markers.
* Gemini CLI / Qwen Code: the "This is the … We are setting up the context"
  preamble.

``human_prompt`` answers "what did the person ask" (titles, intent, turn
anchors). ``is_injected_context`` answers "should this user-role message be
shown as context rather than as the person" and is deliberately narrower: it
fires only on known injected markers, so a slash command or an image-only
message stays the user's. Both are pure and never raise.
"""

from __future__ import annotations

import re
from typing import Any

# Wrappers whose inner text IS the human prompt; the first match wins.
_WRAPPED_PROMPT_RES = (
    re.compile(r"<user_query>\s*(.*?)\s*(?:</user_query>|\Z)", re.S),
    re.compile(r"<realtime_delegation>.*?<input>\s*(.*?)\s*</input>", re.S),
    re.compile(r"^\s*<task>\s*(.*?)\s*(?:</task>|\Z)", re.S),
    # Codex attachment / IDE / in-app-browser heads all end in this line.
    re.compile(r"^## My request(?: for Codex)?:[ \t]*\n(.*)", re.S | re.M),
    # Claude Code ``/goal <prompt>``: the argument is the person's ask.
    re.compile(r"<command-name>/goal</command-name>.*?<command-args>\s*(.*?)\s*"
               r"(?:</command-args>|\Z)", re.S),
)

# Blocks the person attached (pi inlines a file as ``<file name=…>…</file>``):
# skipped to reach the prompt, but never a reason to call a message context.
_ATTACHMENT_TAGS = frozenset({"file"})

# Tags whose whole block is harness context, never the person.
_INJECTED_TAGS = frozenset({
    "environment_context", "user_instructions", "INSTRUCTIONS",
    "permissions instructions", "skills_instructions", "recommended_plugins",
    "in-app-browser-context", "collaboration_mode", "multi_agent_mode",
    "multi_agent_role", "model_switch", "turn_aborted", "system-reminder",
    "task-notification", "local-command-stdout", "local-command-stderr",
    "environment_details", "timestamp", "user_info", "rules",
    "project_layout", "git_status",
})

# Plain-text heads a harness injects in the user role.
_INJECTED_TEXT_PREFIXES = (
    "# AGENTS.md instructions for",
    "Caveat: The messages below were generated by the user while running",
    "This session is being continued from a previous conversation",
    "This is the Gemini CLI. We are setting up the context",
    "This is the Qwen Code. We are setting up the context",
    "[Request interrupted by user",
    "A session-scoped Stop hook is now active",
)

# Texts that can never be a title even when unrecognised: any harness tag
# (``<command-name>``, ``<image …>``), the short "Caveat:" preamble, and a
# Codex attachment/IDE head whose "## My request:" line was cut off.
_NOT_A_PROMPT_PREFIXES = ("<", "Caveat:", "# Files mentioned by the user:",
                          "# Context from my IDE setup:") + _INJECTED_TEXT_PREFIXES

_OPEN_TAG_RE = re.compile(r"<([A-Za-z_][\w\-]*(?: [\w\-]+)?)(?:\s[^>]*)?>")
_ATTACHMENT_PATTERN = r"(?:<image\b[^>]*>|</image>|\[Image: source: [^\]\n]*\])"
_ATTACHMENT_RE = re.compile(r"^\s*" + _ATTACHMENT_PATTERN)
_ATTACHMENT_ANY_RE = re.compile(_ATTACHMENT_PATTERN)


def _text(value: Any) -> str:
    """Flatten a message ``content`` (str or block list) to text."""
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        parts = []
        for block in value:
            if isinstance(block, str):
                parts.append(block)
            elif isinstance(block, dict) and isinstance(block.get("text"), str):
                parts.append(block["text"])
        return "\n".join(parts)
    return ""


def _strip_injected_head(text: str) -> str:
    """Drop leading injected blocks and attachment markers; return the rest."""
    t = text
    while True:
        t = t.lstrip()
        if not t:
            return ""
        m = _ATTACHMENT_RE.match(t)
        if m:
            t = t[m.end():]
            continue
        if t.startswith("# AGENTS.md instructions for"):
            # A header line, then an <INSTRUCTIONS> block the loop drops next.
            nl = t.find("\n")
            t = "" if nl < 0 else t[nl + 1:]
            continue
        m = _OPEN_TAG_RE.match(t)
        if m and (m.group(1) in _INJECTED_TAGS or m.group(1) in _ATTACHMENT_TAGS):
            close = t.find("</" + m.group(1) + ">", m.end())
            # An unclosed injected block (truncated capture) is context to
            # the end: nothing after it can be told apart from it.
            t = "" if close < 0 else t[close + len(m.group(1)) + 3:]
            continue
        return t


def human_prompt(value: Any) -> str:
    """The part of a user-role message the person typed, or "" when there is
    none (pure harness context, an attachment marker, a tag frame). Keeps the
    original line breaks; callers collapse whitespace as they need."""
    try:
        text = _text(value).strip()
        if not text:
            return ""
        for rx in _WRAPPED_PROMPT_RES:
            m = rx.search(text)
            if m:
                inner = m.group(1).strip()
                # A wrapper can hold another frame (an image tag, a reminder).
                return human_prompt(inner) if inner != text else ""
        rest = _strip_injected_head(text).strip()
        if not rest or rest.startswith(_NOT_A_PROMPT_PREFIXES):
            return ""
        # Attachment markers trailing the prompt are never the person.
        return _ATTACHMENT_ANY_RE.sub("", rest).strip()
    except Exception:  # noqa: BLE001 — never crash on bad input
        return ""


def is_injected_context(value: Any) -> bool:
    """True when a user-role message is ONLY harness-injected context: it opens
    on a known injected marker and carries no human prompt after it."""
    try:
        text = _text(value).lstrip()
        if not text:
            return False
        m = _OPEN_TAG_RE.match(text)
        known = (m is not None and m.group(1) in _INJECTED_TAGS) or \
            text.startswith(_INJECTED_TEXT_PREFIXES)
        return known and not human_prompt(text)
    except Exception:  # noqa: BLE001
        return False
