"""Family-runtime session titles from the first real user prompt.

Founder report 2026-07-30: the Conversations tab showed "Untitled session"
for every Claude Code session — ``/api/transcripts`` returned
``{id: "claude_code:UUID", title: ""}`` because (a) the list fast path
re-derived titles from the OpenClaw sessions dir (where family transcripts
don't live) and never read the ingest-persisted ``sessions.title``, and
(b) the ingest-side derivation missed list-block content / the "Caveat:"
resume preamble and clobbered real titles with the raw UUID fallback.

Pins the derivation rule in ``clawmetry/session_titles.py`` (first
qualifying user text; skip "<"-prefixed + "Caveat:" + empty; collapse
whitespace; 80-char cap with ellipsis) and the two consumer paths:
``sync.sync_family_runtimes`` (title persisted on the session row,
no-clobber) and ``/api/transcripts`` (titles actually served).
"""

from __future__ import annotations

import importlib
import json
import time
from unittest.mock import patch

import pytest
from flask import Flask

from clawmetry import session_titles as st
from clawmetry.adapters.base import (
    AgentAdapter,
    Capability,
    DetectResult,
    Event,
    Session,
)


@pytest.fixture(autouse=True)
def _clear_title_cache():
    st._TITLE_CACHE.clear()
    yield
    st._TITLE_CACHE.clear()


def _write_jsonl(path, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(json.dumps(r) for r in rows) + "\n")
    return path


# ── derive_title_from_jsonl: the pinned derivation rule ───────────────────────


def test_plain_user_string(tmp_path):
    p = _write_jsonl(tmp_path / "s.jsonl", [
        {"type": "user", "message": {"role": "user", "content":
         "bump clawmetry cloud to use the latest version of clawmetry oss"}},
        {"type": "assistant", "message": {"role": "assistant", "content": "ok"}},
    ])
    assert st.derive_title_from_jsonl(p) == (
        "bump clawmetry cloud to use the latest version of clawmetry oss"
    )


def test_list_content_blocks(tmp_path):
    p = _write_jsonl(tmp_path / "s.jsonl", [
        {"type": "user", "message": {"role": "user", "content": [
            {"type": "tool_result", "content": "not a title"},
            {"type": "text", "text": "fix the flaky ci matrix"},
        ]}},
    ])
    assert st.derive_title_from_jsonl(p) == "fix the flaky ci matrix"


def test_skips_angle_bracket_and_caveat_texts(tmp_path):
    p = _write_jsonl(tmp_path / "s.jsonl", [
        {"type": "user", "message": {"content": "<system-reminder>stuff</system-reminder>"}},
        {"type": "user", "message": {"content": "<command-name>/clear</command-name>"}},
        {"type": "user", "message": {"content":
         "Caveat: the messages below were generated by the user while running..."}},
        {"type": "user", "message": {"content": "   "}},
        {"type": "user", "message": {"content": "the real first prompt"}},
    ])
    assert st.derive_title_from_jsonl(p) == "the real first prompt"


def test_truncates_to_80_chars_with_ellipsis(tmp_path):
    long = "word " * 40  # 200 chars once collapsed
    p = _write_jsonl(tmp_path / "s.jsonl", [
        {"type": "user", "message": {"content": long}},
    ])
    out = st.derive_title_from_jsonl(p)
    assert out.endswith("…")
    assert len(out) <= 80
    assert out.startswith("word word")


def test_collapses_whitespace(tmp_path):
    p = _write_jsonl(tmp_path / "s.jsonl", [
        {"type": "user", "message": {"content": "  hello\n\n   world\t! "}},
    ])
    assert st.derive_title_from_jsonl(p) == "hello world !"


def test_empty_file_no_title(tmp_path):
    p = tmp_path / "empty.jsonl"
    p.write_text("")
    assert st.derive_title_from_jsonl(p) == ""


def test_missing_file_never_raises(tmp_path):
    assert st.derive_title_from_jsonl(tmp_path / "nope.jsonl") == ""


def test_non_json_lines_skipped(tmp_path):
    p = tmp_path / "s.jsonl"
    p.write_text('not json\n{"type": "user", "message": {"content": "hi there"}}\n')
    assert st.derive_title_from_jsonl(p) == "hi there"


# ── event-based derivation (codex/cursor/… ride the same ingest path) ─────────


def _ev(role, content, i=0):
    return Event(agent="x", session_id="s", id=f"e{i}", type="message",
                 ts=float(i), role=role, content=content)


def test_events_prefer_user_role():
    evs = [_ev("assistant", "I will start by reading the file", 0),
           _ev("user", "add a dark mode toggle", 1)]
    assert st.derive_title_from_family_events(evs) == "add a dark mode toggle"


def test_events_skip_plumbing_texts():
    evs = [_ev("user", "<local-command-stdout>ok</local-command-stdout>", 0),
           _ev("user", "Caveat: resumed session preamble", 1),
           _ev("user", "ship the release notes", 2)]
    assert st.derive_title_from_family_events(evs) == "ship the release notes"


def test_events_roleless_fallback():
    # Adapters that don't stamp roles keep their legacy any-text titling.
    evs = [_ev("", "investigate the login timeout", 0)]
    assert st.derive_title_from_family_events(evs) == "investigate the login timeout"


def test_events_empty_never_raises():
    assert st.derive_title_from_family_events([]) == ""
    assert st.derive_title_from_family_events(None) == ""


# ── looks_like_session_id (the no-clobber discriminator) ─────────────────────


def test_id_like_titles():
    uuid = "e149acae-1a2b-4c3d-8e9f-0a1b2c3d4e5f"
    assert st.looks_like_session_id("", "x")
    assert st.looks_like_session_id(uuid, f"claude_code:{uuid}")
    assert st.looks_like_session_id(f"claude_code:{uuid}", f"claude_code:{uuid}")
    # sid[:40] truncation (what the list path stores as "name")
    assert st.looks_like_session_id(f"claude_code:{uuid}"[:40], f"claude_code:{uuid}")
    assert not st.looks_like_session_id("fix the flaky ci matrix", f"claude_code:{uuid}")


# ── integration: ingest persists the derived title on the session row ─────────


_UUID1 = "aaaaaaaa-1111-2222-3333-444444444444"
_UUID2 = "bbbbbbbb-1111-2222-3333-444444444444"


def _fake_cc_adapter(sessions, events_by_sid):
    class _FakeCC(AgentAdapter):
        name = "claude_code"
        display_name = "Claude Code"

        def detect(self):
            return DetectResult(name=self.name, display_name=self.display_name,
                                detected=True, session_count=len(sessions))

        def list_sessions(self, limit=100):
            return sessions

        def list_events(self, session_id, limit=500):
            return events_by_sid.get(session_id, [])

        def capabilities(self):
            return {Capability.SESSIONS, Capability.EVENTS}

    return _FakeCC


@pytest.fixture
def isolated_sync(tmp_path, monkeypatch):
    monkeypatch.setenv("CLAWMETRY_LOCAL_STORE_PATH", str(tmp_path / "events.duckdb"))
    monkeypatch.setenv("CLAWMETRY_LOCAL_FLUSH_SECS", "0.05")
    # Point Claude Code transcript discovery at an isolated projects root.
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(tmp_path / "claude"))
    # Keep the OpenClaw spawned-session index lookup off the dev machine.
    monkeypatch.setenv("CLAWMETRY_OPENCLAW_DIR", str(tmp_path / ".openclaw"))
    import clawmetry.local_store as ls
    import clawmetry.sync as sync
    importlib.reload(ls)
    importlib.reload(sync)
    # In-process writer on the tmp DB (a live dev-box daemon would otherwise
    # proxy to the PROD store — same guard as test_family_runtime_ingest).
    monkeypatch.setattr(ls, "_daemon_registered", lambda: False)
    monkeypatch.delenv("CLAWMETRY_ROLE", raising=False)
    yield sync, ls, tmp_path
    try:
        ls.get_store().stop(flush=True)
    except Exception:
        pass


def _wait_for_flush(store, timeout=3.0):
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if store.health()["ring_depth"] == 0:
            return
        time.sleep(0.02)


def test_planted_jsonl_yields_titled_session_row(isolated_sync):
    """Events carry only plumbing text, but the planted ~/.claude transcript
    head titles the session row (the ground-truth path)."""
    sync, ls, tmp_path = isolated_sync
    _write_jsonl(
        tmp_path / "claude" / "projects" / "-tmp-proj" / f"{_UUID1}.jsonl",
        [
            {"type": "user", "message": {"content": "<command-name>/model</command-name>"}},
            {"type": "user", "message": {"content":
             "bump clawmetry cloud to use the latest version of clawmetry oss"}},
        ],
    )
    sessions = [Session(agent="claude_code", id=_UUID1, started_at=1000.0,
                        ended_at=1010.0, message_count=1)]
    events = {_UUID1: [_ev("user", "<system-reminder>plumbing</system-reminder>", 0)]}
    with patch.object(sync, "_family_adapter_classes",
                      lambda: [_fake_cc_adapter(sessions, events)]), \
         patch.object(sync, "_sync_allowed", return_value=True), \
         patch.object(sync, "_post", return_value={}):
        sync.sync_family_runtimes({"node_id": "n", "api_key": None}, {}, {})
    store = ls.get_store()
    _wait_for_flush(store)
    rows = store._fetch(
        "SELECT title FROM sessions WHERE session_id = ?",
        [f"claude_code:{_UUID1}"],
    )
    assert rows, "session row missing"
    assert rows[0][0] == (
        "bump clawmetry cloud to use the latest version of clawmetry oss"
    )


def test_ingest_never_clobbers_real_title(isolated_sync):
    """A re-ingest pass with nothing derivable must keep the existing human
    title (the legacy s.id fallback used to overwrite it with a UUID)."""
    sync, ls, _tmp = isolated_sync
    store = ls.get_store()
    sid = f"claude_code:{_UUID2}"
    store.ingest_session({"session_id": sid, "title": "a real human title",
                          "started_at": "2026-07-30T00:00:00Z"})
    sessions = [Session(agent="claude_code", id=_UUID2, started_at=1000.0,
                        ended_at=1010.0, message_count=1)]
    events = {_UUID2: [_ev("user", "<system-reminder>plumbing</system-reminder>", 0)]}
    with patch.object(sync, "_family_adapter_classes",
                      lambda: [_fake_cc_adapter(sessions, events)]), \
         patch.object(sync, "_sync_allowed", return_value=True), \
         patch.object(sync, "_post", return_value={}):
        sync.sync_family_runtimes({"node_id": "n", "api_key": None}, {}, {})
    _wait_for_flush(store)
    rows = store._fetch(
        "SELECT title FROM sessions WHERE session_id = ?", [sid])
    assert rows and rows[0][0] == "a real human title"


# ── integration: /api/transcripts serves the titles ──────────────────────────


@pytest.fixture
def transcripts_app(tmp_path, monkeypatch):
    monkeypatch.setenv("CLAWMETRY_LOCAL_STORE_PATH", str(tmp_path / "events.duckdb"))
    monkeypatch.setenv("CLAWMETRY_LOCAL_FLUSH_SECS", "0.05")
    monkeypatch.setenv("CLAWMETRY_LOCAL_STORE_READ", "1")
    monkeypatch.setenv("CLAUDE_CONFIG_DIR", str(tmp_path / "claude"))

    import clawmetry.local_store as ls
    importlib.reload(ls)
    # In-process writer on the tmp DB (a live dev-box daemon would otherwise
    # hand back a _ProxyStore to the PROD store).
    monkeypatch.setattr(ls, "_daemon_registered", lambda: False)
    monkeypatch.delenv("CLAWMETRY_ROLE", raising=False)
    import routes.sessions as sessions_mod
    importlib.reload(sessions_mod)

    # Force the daemon-proxy lookup to miss so the route reads the
    # in-process store seeded here (same guard as
    # test_transcripts_list_detail_count_parity).
    import routes.local_query as lq
    monkeypatch.setattr(lq, "_DISCOVERY_PATH",
                        str(tmp_path / "no-such-discovery.json"))
    lq._DAEMON_CACHE["disc"] = None
    lq._DAEMON_CACHE["ts"] = 0.0

    a = Flask(__name__)
    a.register_blueprint(sessions_mod.bp_sessions)
    yield a, ls, tmp_path
    try:
        ls.get_store().stop(flush=True)
    except Exception:
        pass


def _msg_event(event_id, sid, role, content, ts):
    return {
        "id": event_id, "node_id": "n", "agent_id": "main", "session_id": sid,
        "event_type": "message", "ts": ts,
        "data": json.dumps({"role": role, "content": content, "timestamp": ts}),
    }


def test_transcripts_serve_family_titles(transcripts_app):
    a, ls, tmp_path = transcripts_app
    store = ls.get_store()
    sid1 = f"claude_code:{_UUID1}"  # titled via the sessions-table join
    sid2 = f"claude_code:{_UUID2}"  # titled via the planted-JSONL fallback

    store.ingest(_msg_event("t1", sid1, "user", "hi", "2026-07-30T10:00:00Z"))
    store.ingest(_msg_event("t2", sid2, "user", "hi", "2026-07-30T11:00:00Z"))
    store.ingest_session({"session_id": sid1, "title": "wire the usage anomaly chart",
                          "started_at": "2026-07-30T10:00:00Z",
                          "last_active_at": "2026-07-30T10:00:00Z"})
    # sid2's stored title is the legacy UUID fallback — must NOT be served.
    store.ingest_session({"session_id": sid2, "title": _UUID2,
                          "started_at": "2026-07-30T11:00:00Z",
                          "last_active_at": "2026-07-30T11:00:00Z"})
    _write_jsonl(
        tmp_path / "claude" / "projects" / "-tmp-proj" / f"{_UUID2}.jsonl",
        [{"type": "user", "message": {"content": "refactor the cron health summary"}}],
    )
    store._flush_now()
    _wait_for_flush(store)

    body = a.test_client().get("/api/transcripts").get_json()
    assert body.get("_source") == "local_store"
    by_id = {t["id"]: t for t in body["transcripts"]}
    assert by_id[sid1]["title"] == "wire the usage anomaly chart"
    assert by_id[sid2]["title"] == "refactor the cron health summary"
