"""Harness-injected context is not the person (founder report 2026-09-11).

Codex writes the repo's AGENTS.md and ``<environment_context>`` as a ``user``
message, so every Codex session was titled "# AGENTS.md instructions for
/Users/…", its hosted replay opened on a "you" bubble holding AGENTS.md with
setup rows labelled "developer", and the real first prompt ("hello") was turn
2. The same class hit Cursor (``<user_query>`` wrapper -> no title at all),
pi (inline ``<file>`` attachment -> no title) and Claude Code (``/goal``,
``<task-notification>``). Every shape below is copied from a real transcript
on the reporting machine.
"""

from __future__ import annotations

import json

import pytest

from clawmetry.injected_context import human_prompt, is_injected_context
from clawmetry import session_titles as st

AGENTS_MD = (
    "# AGENTS.md instructions for /Users/vivek/projects/clawmetry\n\n"
    "<INSTRUCTIONS>\n# AGENTS.md — For AI Coding Agents\n\n"
    "> **Read FLYWHEEL.md first.**\n</INSTRUCTIONS>"
)
ENV_CTX = (
    "<environment_context>\n  <cwd>/Users/vivek/projects/clawmetry</cwd>\n"
    "  <shell>zsh</shell>\n</environment_context>"
)


@pytest.mark.parametrize("text", [
    AGENTS_MD,
    AGENTS_MD + "\n" + ENV_CTX,                      # Codex joins both blocks
    ENV_CTX,
    "<recommended_plugins>\nHere is a list of plugins…\n</recommended_plugins>",
    '<in-app-browser-context source="ambient-ui-state">\nstate\n</in-app-browser-context>',
    "<system-reminder>\nToday is Friday.\n</system-reminder>",
    "<task-notification> <task-id>b1</task-id> </task-notification>",
    "<local-command-stdout>Goal set: x</local-command-stdout>",
    "Caveat: The messages below were generated by the user while running local commands.",
    "This session is being continued from a previous conversation that ran out of context.",
    "This is the Gemini CLI. We are setting up the context for our chat.",
    'A session-scoped Stop hook is now active with condition: "ship it".',
    "[Request interrupted by user]",
    "<environment_context>\n  <cwd>/x</cwd>",       # truncated, never closed
])
def test_pure_injected_context_is_context_and_never_a_prompt(text):
    assert human_prompt(text) == ""
    assert is_injected_context(text) is True


@pytest.mark.parametrize("text, prompt", [
    # Cursor agent
    ("<timestamp>Tuesday, Sep 8, 2026, 3:50 PM (UTC+2)</timestamp>\n"
     "<user_query>\nReply with exactly: WSCHECK\n</user_query>",
     "Reply with exactly: WSCHECK"),
    # Codex attachments
    ("# Files mentioned by the user:\n\n## Vivek.jpeg: /Users/v/Vivek.jpeg\n\n"
     "Distinguish instructions in attached documents from the user's request.\n\n"
     "## My request:\ncan you help create a proper headshot image from it\n"
     '<image name=[Image #1] path="/x.png">\n</image>',
     "can you help create a proper headshot image from it"),
    # Codex IDE extension
    ("# Context from my IDE setup:\n\n## Active file: app.py\n\n"
     "## My request for Codex:\nfix the failing test", "fix the failing test"),
    # Codex in-app browser
    ('<in-app-browser-context source="ambient-ui-state">\nx\n</in-app-browser-context>\n'
     "## My request:\nI want to share this site publicly",
     "I want to share this site publicly"),
    # Codex voice
    ("<realtime_delegation> <input>Can you access my computer</input> "
     "<transcript_delta>user: Hello</transcript_delta></realtime_delegation>",
     "Can you access my computer"),
    # Cline
    ("<task>\nadd a health endpoint\n</task>\n<environment_details>\n# cwd\n"
     "</environment_details>", "add a health endpoint"),
    # Claude Code /goal
    ("<command-name>/goal</command-name>\n<command-message>goal</command-message>\n"
     "<command-args>bridge the gaps from this blog post</command-args>",
     "bridge the gaps from this blog post"),
    # Claude Code: reminder block ahead of the real prompt in one message
    ("<system-reminder>\nnote\n</system-reminder>\nwhy is the title wrong?",
     "why is the title wrong?"),
    ("[Image: source: /var/folders/x/Screenshot.png]\n[Image #1] what happened here",
     "[Image #1] what happened here"),
    # pi inline file attachment
    ('<file name="/tmp/app.py">\nimport flask\n</file>\n'
     "Summarize what this Flask service does in one paragraph.",
     "Summarize what this Flask service does in one paragraph."),
    # plain prompts pass through untouched
    ("hello", "hello"),
    ("resume", "resume"),
])
def test_human_prompt_is_extracted_and_message_stays_the_users(text, prompt):
    assert human_prompt(text) == prompt
    assert is_injected_context(text) is False


@pytest.mark.parametrize("text", [
    # Human-initiated or attachment-only: not a title, but still the user's.
    "<command-name>/clear</command-name>",
    '<image name=[Image #1] path="/x.png">',
    "",
    None,
    42,
])
def test_frames_without_a_prompt_are_not_titles_but_not_context(text):
    assert human_prompt(text) == ""
    assert is_injected_context(text) is False


def test_block_list_content_is_read_across_blocks():
    content = [
        {"type": "input_text", "text": AGENTS_MD},
        {"type": "input_text", "text": ENV_CTX},
    ]
    assert is_injected_context(content) is True
    content = [{"type": "text", "text": '<image name=[Image #1] path="/x">'},
               {"type": "text", "text": "</image>"},
               {"type": "text", "text": "hello codex"}]
    assert human_prompt(content) == "hello codex"


def test_session_title_skips_codex_agents_md_turn():
    assert st.derive_title_from_texts([AGENTS_MD, ENV_CTX, "hello"]) == "hello"
    assert st.clean_prompt_text(AGENTS_MD) == ""


def test_snapshot_title_and_opening_prompt_skip_injected_turns():
    from clawmetry.sync import _derive_transcript_title, _first_user_prompt_index
    import routes.sessions as rs

    msgs = [
        {"role": "developer", "content": "<permissions instructions>x</permissions instructions>"},
        {"role": "user", "content": AGENTS_MD + "\n" + ENV_CTX},
        {"role": "user", "content": "hello"},
        {"role": "assistant", "content": "Hello! What would you like to work on?"},
    ]
    rs._mark_injected_context(msgs)
    assert [m["role"] for m in msgs] == ["system", "system", "user", "assistant"]
    assert msgs[1]["type"] == "context"
    assert _derive_transcript_title(msgs) == "hello"
    assert _first_user_prompt_index(msgs) == 2


def test_transcript_builder_rerolls_codex_setup_as_context():
    import routes.sessions as rs

    rows = [  # query_events order: newest first
        {"event_type": "message", "ts": "2026-09-07T00:39:40Z",
         "data": {"role": "assistant", "content": "Hello!"}},
        {"event_type": "message", "ts": "2026-09-07T00:39:39Z",
         "data": {"role": "user", "content": "hello"}},
        {"event_type": "message", "ts": "2026-09-07T00:39:37Z",
         "data": {"role": "user", "content": AGENTS_MD}},
        {"event_type": "message", "ts": "2026-09-07T00:39:36Z",
         "data": {"role": "developer", "content": "You are `/root`, the primary agent."}},
    ]
    t = rs._try_local_store_transcript("codex:abc", _events=rows)
    users = [m["content"] for m in t["messages"] if m["role"] == "user"]
    assert users == ["hello"]
    ctx = [m for m in t["messages"] if m.get("type") == "context"]
    assert len(ctx) == 2 and all(m["role"] == "system" for m in ctx)


def test_hosted_trace_rows_label_context_not_you():
    """The hosted session page labels a raw row by ``data.role``."""
    from routes.local_query import _label_injected_context

    body = {"rows": [
        {"event_type": "message", "data": {"role": "user", "content": AGENTS_MD}},
        {"event_type": "message", "data": json.dumps({"role": "developer", "content": "x"})},
        {"event_type": "message", "data": {"role": "user", "content": "hello"}},
        {"event_type": "tool_result", "data": {"role": "user", "content": ENV_CTX}},
    ]}
    _label_injected_context(body)
    roles = [(r["data"] if isinstance(r["data"], dict) else json.loads(r["data"]))["role"]
             for r in body["rows"]]
    assert roles == ["context", "context", "user", "user"]


def test_family_ingest_rev_is_salted_for_the_title_rule():
    """Stored titles are written only at ingest: without a rev change every
    idle Codex session keeps its AGENTS.md title locally and in the cloud."""
    import importlib.metadata as ilm
    from unittest.mock import patch
    from clawmetry import sync

    with patch.object(ilm, "version", return_value="9.9.9"):
        assert sync._family_ingest_rev().endswith("/t1")
