#!/usr/bin/env python3
"""Atheris harness for `clawmetry.event_shape` transcript classification.

Session transcripts are JSONL written by the agent runtimes, not by ClawMetry,
so their shape is theirs to change and a half-written line is normal. Contract
asserted: `classify` and `typed_columns` never raise. See
`tests/fuzz/README.md`.

    pip install atheris
    python3 tests/fuzz/fuzz_event_shape.py -atheris_runs=200000
"""

import json
import sys

import atheris
from _contracts import check_event_shape


def TestOneInput(data: bytes) -> None:
    fdp = atheris.FuzzedDataProvider(data)
    event_type = fdp.ConsumeUnicodeNoSurrogates(32)
    raw = fdp.ConsumeBytes(fdp.remaining_bytes())

    # Feed the decoder both shapes it sees in practice: a parsed JSON object
    # from a well-formed transcript line, and the raw string from a line that
    # did not parse. Roughly half of fuzzer-generated bytes are not valid JSON,
    # so without the fallback most runs would only ever exercise the str path.
    try:
        payload = json.loads(raw.decode("utf-8", "surrogatepass"))
    except (ValueError, UnicodeDecodeError):
        payload = raw.decode("utf-8", "replace")

    check_event_shape(event_type, payload)


def main() -> None:
    atheris.Setup(sys.argv, TestOneInput, enable_python_coverage=True)
    atheris.Fuzz()


if __name__ == "__main__":
    # `_contracts` resolves because Python puts this script's directory on
    # sys.path[0] when the file is run directly, which is the only way a
    # libFuzzer harness is ever launched.
    main()
