"""routes/entitlement -- the entitlement API surface (split from a 1.84 MB file).

Re-exports the full flat namespace so routes.entitlement.<anything> resolves
exactly as before for the 297 modules that import it.

Key symbols: bp_entitlement, _ping_paywall_lifecycle,
_PAYWALL_LIFECYCLE_EVENTS, _MINIMAL_OSS_FREE_SNAPSHOT.

See _shared.py for the blueprint, constants, and all 150 non-handler helpers;
_endpoints_01 through _endpoints_08 for the 434 route handlers in their
original order.  dashboard.py does from routes.entitlement import bp_entitlement
and every entitlement test that patches a helper targets routes.entitlement._shared.
"""


# _shared first: it defines bp_entitlement, which every part decorates with.
from ._shared import *  # noqa: F401,F403
from ._shared import (  # noqa: F401
    _CAPACITY_PARAMS,
    _EMPTY_RUNTIME_DETECTION,
    _HAS_ALL_AT_KEYS,
    _MINIMAL_OSS_FREE_SNAPSHOT,
    _MISSING_ALL_AT_KEYS,
    _PAYWALL_DISTINCT_DIMS,
    _PAYWALL_LIFECYCLE_EVENTS,
    _activate_envelope,
    _bundle_batch_path_row_out,
    _capacity_batch_row_to_body,
    _deactivate_envelope,
    _has_all_at_batch_body,
    _has_all_at_batch_fallback,
    _has_all_at_body,
    _has_all_at_fallback,
    _has_all_at_path_batch_body,
    _has_all_at_path_batch_fallback,
    _has_all_at_path_body,
    _has_all_at_path_fallback,
    _has_all_body,
    _has_all_bundle_at_path_batch_fallback,
    _has_all_bundle_at_path_fallback,
    _has_all_bundle_batch_at_path_fallback,
    _has_all_bundle_from_path_batch_fallback,
    _has_all_bundle_row_at_to_body,
    _has_all_bundle_row_to_body,
    _has_all_fallback,
    _has_all_from_path_batch_body,
    _has_all_from_path_batch_fallback,
    _has_axis_at_body,
    _has_axis_at_fallback,
    _has_axis_body,
    _has_axis_fallback,
    _has_batch_at_fallback,
    _has_batch_fallback,
    _has_batch_rollup,
    _has_bundle_at_batch_body,
    _has_bundle_at_batch_fallback,
    _has_bundle_at_body,
    _has_bundle_at_fallback,
    _has_bundle_at_path_batch_body,
    _has_bundle_at_path_batch_fallback,
    _has_bundle_at_path_body,
    _has_bundle_at_path_fallback,
    _has_bundle_body,
    _has_bundle_fallback,
    _has_bundle_from_path_batch_body,
    _has_bundle_from_path_batch_fallback,
    _has_bundle_row_at_body,
    _has_bundle_row_body,
    _has_capacity_at_batch_body,
    _has_capacity_at_batch_fallback,
    _has_capacity_at_batch_row_to_body,
    _has_channel_count_at_fallback,
    _has_channel_count_batch_fallback,
    _has_channel_count_batch_row_to_body,
    _has_channel_count_fallback,
    _has_node_count_at_batch_fallback,
    _has_node_count_at_batch_row_to_body,
    _has_node_count_at_fallback,
    _has_node_count_batch_fallback,
    _has_node_count_batch_row_to_body,
    _has_node_count_fallback,
    _has_retention_window_at_fallback,
    _has_retention_window_batch_fallback,
    _has_retention_window_batch_row_to_body,
    _has_retention_window_fallback,
    _license_expires_snapshot,
    _license_expiry_snapshot,
    _license_features_at_snapshot,
    _license_gate_snapshot,
    _license_issued_snapshot,
    _license_nodes_snapshot,
    _license_permissions_snapshot,
    _license_presence_snapshot,
    _license_pubkey_fingerprint_snapshot,
    _license_state_at_snapshot,
    _license_state_snapshot,
    _license_subject_at_snapshot,
    _license_subject_snapshot,
    _license_tier_at_snapshot,
    _license_tier_snapshot,
    _min_tier_for_all_row_to_body,
    _min_tier_for_bundle_row_to_body,
    _min_tier_for_capacity_at_batch_body,
    _min_tier_for_capacity_at_batch_fallback,
    _min_tier_for_capacity_at_body,
    _min_tier_for_capacity_at_fallback,
    _min_tier_for_capacity_batch_fallback,
    _min_tier_for_capacity_body,
    _min_tier_for_capacity_fallback,
    _missing_all_at_batch_body,
    _missing_all_at_batch_fallback,
    _missing_all_at_body,
    _missing_all_at_fallback,
    _missing_all_at_path_batch_body,
    _missing_all_at_path_batch_fallback,
    _missing_all_at_path_body,
    _missing_all_at_path_fallback,
    _missing_all_body,
    _missing_all_bundle_at_path_batch_fallback,
    _missing_all_bundle_at_path_fallback,
    _missing_all_bundle_batch_at_path_fallback,
    _missing_all_bundle_from_path_batch_fallback,
    _missing_all_bundle_row_at_to_body,
    _missing_all_bundle_row_to_body,
    _missing_all_fallback,
    _missing_all_from_path_batch_body,
    _missing_all_from_path_batch_fallback,
    _missing_bundle_at_batch_body,
    _missing_bundle_at_batch_fallback,
    _missing_bundle_at_body,
    _missing_bundle_at_fallback,
    _missing_bundle_at_path_batch_body,
    _missing_bundle_at_path_batch_fallback,
    _missing_bundle_at_path_body,
    _missing_bundle_at_path_fallback,
    _missing_bundle_body,
    _missing_bundle_fallback,
    _missing_bundle_from_path_batch_body,
    _missing_bundle_from_path_batch_fallback,
    _missing_bundle_row_at_body,
    _missing_bundle_row_body,
    _neighbour_tier_headroom_envelope,
    _next_prev_lock_reason,
    _next_prev_lock_reason_at,
    _next_prev_lock_reason_at_batch,
    _next_prev_lock_reason_batch,
    _next_prev_lock_reason_batch_grace_body,
    _next_prev_lock_reason_grace_body,
    _next_prev_tier_axis_catalog_grace_body,
    _next_prev_tier_axis_spec_batch_grace_body,
    _next_prev_tier_axis_spec_grace_body,
    _next_prev_tier_channel_catalog_grace_body,
    _next_prev_tier_channel_spec_at_batch,
    _next_prev_tier_feature_spec_at_batch,
    _next_prev_tier_runtime_spec_at_batch,
    _parse_aggregate_bundles_body,
    _parse_bundles_body,
    _parse_capacity_arg,
    _parse_capacity_batch_csv,
    _parse_csv_arg,
    _parse_from_tiers_bundle_body,
    _parse_license_days_csv,
    _parse_license_epochs_csv,
    _parse_single_bundle_body,
    _parse_tiers_for_capacity_batch_csv,
    _perspective_envelope,
    _perspective_fallback,
    _ping_paywall_lifecycle,
    _pro_install_snapshot,
    _resolver_envelope,
    _route_actor,
    _runtime_detection_counts,
    _tiers_for_capacity_perval_at_body,
    _tiers_for_capacity_perval_at_fallback,
    _tiers_for_capacity_perval_fallback,
)
from ._endpoints_01 import *  # noqa: F401,F403
from ._endpoints_02 import *  # noqa: F401,F403
from ._endpoints_03 import *  # noqa: F401,F403
from ._endpoints_04 import *  # noqa: F401,F403
from ._endpoints_05 import *  # noqa: F401,F403
from ._endpoints_06 import *  # noqa: F401,F403
from ._endpoints_07 import *  # noqa: F401,F403
from ._endpoints_08 import *  # noqa: F401,F403

__all__ = ["bp_entitlement"]
