#!/usr/bin/env python3
"""Generate docs/ATLAS_OPENCLAW_SCORECARD.md from the ATLAS OpenClaw replay.

vivekchand/clawmetry#5944. The scorecard is never hand-written: it is rendered
from ``tests/replay/atlas_openclaw/`` run through the real detectors, workspace
scanner, policy engine and call classifier, so it cannot claim a catch the code
no longer makes.

Usage:
  python3 scripts/gen_atlas_openclaw_scorecard.py            # rewrite the doc
  python3 scripts/gen_atlas_openclaw_scorecard.py --check    # CI: exit 1 on drift
  python3 scripts/gen_atlas_openclaw_scorecard.py --bundle out.json
      # redacted, reproducible evidence bundle for this run
  python3 scripts/gen_atlas_openclaw_scorecard.py --verify-atlas ATLAS-2026.08.yaml
      # re-check every pinned case and procedure step against MITRE's data file
      # (needs PyYAML; not run in CI, which has no network)
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import os
import sys
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.normpath(os.path.join(HERE, ".."))
SUITE_DIR = os.path.join(REPO_ROOT, "tests", "replay", "atlas_openclaw")
DOC_PATH = os.path.join(REPO_ROOT, "docs", "ATLAS_OPENCLAW_SCORECARD.md")


def load_replay():
    spec = importlib.util.spec_from_file_location(
        "atlas_openclaw_replay", os.path.join(SUITE_DIR, "replay.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_OUTCOME_LABEL = {
    "unobservable": "unobservable",
    "observed": "observed",
    "partial": "partial",
    "detected": "detected",
    "held_before_action": "held before action",
    "quiet": "quiet",
    "false_positive": "FALSE POSITIVE",
}
_VARIANT_LABEL = {"cold_start": "cold start", "learned_baseline": "learned baseline"}


def _cell(text) -> str:
    return str(text if text not in (None, "") else "none").replace("|", "\\|").replace("\n", " ")


def _findings(stage: dict) -> str:
    items = [f"`{f['kind']}` {f['severity']}" for f in stage.get("findings") or []]
    return ", ".join(items) if items else "none"


def _decisions(stage: dict) -> str:
    items = [f"{d['action']} via `{d['policy_id']}` ({d['evidence_level']})"
             for d in stage.get("decisions") or []]
    return ", ".join(items) if items else "none"


def _pre_tool(stage: dict) -> str:
    p = stage.get("pre_tool")
    if not p:
        return "no tool call"
    return f"{p['level']}: {p['reason']}"


def render(report: dict) -> str:
    atlas = report["atlas"]
    cases = {c["id"]: c for c in report["cases"]}
    scenarios = report["scenarios"]
    attacks = [s for s in scenarios if s["type"] == "attack"]
    controls = [s for s in scenarios if s["type"] == "control"]
    variants = []
    for s in scenarios:
        for vid in s["variants"]:
            if vid not in variants:
                variants.append(vid)

    L = []
    w = L.append
    w("# MITRE ATLAS OpenClaw case studies: Guard replay scorecard")
    w("")
    w("<!-- GENERATED by scripts/gen_atlas_openclaw_scorecard.py from "
      "tests/replay/atlas_openclaw/. Do not edit by hand; CI runs --check. -->")
    w("")
    w("> **Evidence tier: fixture replay.** Recorded and synthetic session events were "
      "fed to Guard's real detectors, workspace scan, policy engine and call classifier. "
      "No agent ran, no payload executed and no control acted. **This scorecard does not "
      "establish protection against CVE-2026-25253, and it does not establish protection "
      "against prompt injection in general.** A stage can only be scored held before action "
      "by the isolated execution tier, which has not been run.")
    w("")
    w("Tracking issue: vivekchand/clawmetry#5944.")
    w("")

    w("## What was replayed")
    w("")
    w("| Pin | Value |")
    w("|---|---|")
    w(f"| ATLAS edition | {atlas['edition']} |")
    w(f"| ATLAS source | `{atlas['path']}` in {atlas['repository']}, git blob `{atlas['git_blob']}` |")
    w("| ATLAS mappings pinned | case study, every procedure step with its technique and tactic, and the "
      "mitigations ATLAS publishes against those techniques. ATLAS links mitigations to techniques, not to "
      "case studies, so each case's mitigation list is **derived**, not published by MITRE for the case |")
    w("| Source report | **not pinned.** MITRE's OpenClaw investigation report PR-26-00176-1 (named in the "
      "tracking issue) is not in the ATLAS data file and was not retrieved, so nothing here is checked "
      "against it (NX-5) |")
    w(f"| Scenario suite | `{report['suite_version']}` |")
    w(f"| Policy set | `{report['policy_set']}` |")
    w("| Runtimes | " + ", ".join(sorted({s['runtime'] for s in scenarios})) + " |")
    w("| Operating system | not a factor: pure replay, no process is started |")
    w("| Product version | the commit this file is committed at. CI regenerates the "
      "scorecard on every change and fails when it differs |")
    w("")
    w("| Case study | Name | ATLAS modified | Actor | Scenario |")
    w("|---|---|---|---|---|")
    by_case = {s["case"]: s for s in attacks}
    for cid in sorted(cases):
        c = cases[cid]
        sc = by_case.get(cid)
        w(f"| {cid} | {_cell(c['name'])} | {c['modified_date']} | {_cell(c['actor'])} | "
          f"`{sc['id'] if sc else 'none'}` |")
    w("")

    w("## How to read it")
    w("")
    w("Each stage is one or more consecutive ATLAS procedure steps, scored on its own:")
    w("")
    w("- **unobservable**: nothing in the stage reaches a path ClawMetry reads.")
    w("- **observed**: the activity is recorded, and no finding fires.")
    w("- **partial**: a finding fires, but below the severity the stage calls for, or of a kind it did not name.")
    w("- **detected**: a named finding fires at or above the severity the stage calls for.")
    w("- **held before action**: a control stopped the action before it ran, shown by a real receipt. Never assigned here.")
    w("")
    w("A case is **caught** when its decisive stage is detected, **partial** when any stage is partial or "
      "better, and **missed** otherwise. Every chain is replayed twice: **cold start** (no history, as on "
      "a fresh install) and **learned baseline** (40 earlier sessions whose hosts Guard has learned). "
      "Findings are produced after the call they describe, on the daemon's next pass, so no finding here "
      "stopped anything. Policy decisions are **configured**: a policy matched, and no actuator ran. "
      "The pre-tool column is the risk ClawMetry's call classifier assigns; it is a classification, "
      "not a hold.")
    w("")

    w("## Summary")
    w("")
    w("| Case study | Decisive stage | " + " | ".join(_VARIANT_LABEL.get(v, v) for v in variants) + " |")
    w("|---|---|" + "---|" * len(variants))
    for sc in sorted(attacks, key=lambda s: s["case"]):
        cells = [sc["variants"][v]["verdict"] if v in sc["variants"] else "n/a" for v in variants]
        w(f"| {sc['case']} | {sc['decisive_stage']} | " + " | ".join(f"**{c}**" for c in cells) + " |")
    w("")
    total_fp = sum(1 for s in controls for v in s["variants"].values()
                   for st in v["stages"] if st["outcome"] == "false_positive")
    w(f"Benign controls: {len(controls)} scenarios, {total_fp} false positive(s).")
    w("")

    scen_src = {}
    for path in sorted(os.listdir(os.path.join(SUITE_DIR, "scenarios"))):
        with open(os.path.join(SUITE_DIR, "scenarios", path), encoding="utf-8") as f:
            raw = json.load(f)
        scen_src[raw["id"]] = raw

    for sc in sorted(attacks, key=lambda s: s["case"]):
        c = cases[sc["case"]]
        raw = scen_src[sc["id"]]
        steps = {s["step"]: s for s in c["steps"]}
        w(f"## {sc['case']}: {c['name']}")
        w("")
        w(raw.get("summary", ""))
        w("")
        w(f"Runtime `{sc['runtime']}`. Sources: " + ", ".join(c["references"]) + ".")
        w("")
        w(f"Decisive stage **{sc['decisive_stage']}**: {raw.get('decisive_reason', '')}")
        w("")
        w("| Stage | ATLAS techniques | What happens | " +
          " | ".join(_VARIANT_LABEL.get(v, v) for v in variants) +
          " | Findings (learned baseline) | First flagged | Policy decision | Pre-tool classification |")
        w("|---|---|---|" + "---|" * len(variants) + "---|---|---|---|")
        stage_ids = [st["id"] for st in next(iter(sc["variants"].values()))["stages"]]
        for i, stid in enumerate(stage_ids):
            rows = {v: sc["variants"][v]["stages"][i] for v in sc["variants"]}
            ref = rows.get("learned_baseline") or next(iter(rows.values()))
            techs = "<br>".join(
                f"{s} `{steps[s]['technique']}` {steps[s]['technique_name']}"
                for s in ref["steps"] if s in steps)
            w(f"| {stid} | {techs} | {_cell(ref['title'])} | " +
              " | ".join(_OUTCOME_LABEL.get(rows[v]["outcome"], rows[v]["outcome"])
                         if v in rows else "n/a" for v in variants) +
              f" | {_findings(ref)} | {_cell(ref['first_flagged_ts'])} | {_decisions(ref)} | "
              f"{_cell(_pre_tool(ref))} |")
        w("")
        w("Why each stage scored as it did:")
        w("")
        for st in raw["stages"]:
            w(f"- **{st['id']}**: {st.get('basis', '')}")
        for nr in raw.get("not_replayed") or []:
            w(f"- **{', '.join(nr['steps'])}** (not replayed): {nr['reason']}")
        w("")
        mits = c.get("mitigations") or []
        w(f"ATLAS mitigations published against this case's step techniques (derived, {len(mits)}): " +
          ("; ".join(f"`{mt['id']}` {_cell(mt['name'])} ({', '.join(mt['techniques'])})" for mt in mits)
           if mits else "none") + ". A listed mitigation is MITRE's guidance, not a ClawMetry control.")
        w("")

    w("## Benign controls")
    w("")
    w("A control uses the same tools and files as an attack and must stay quiet. "
      "`codex-only-kill` in the policy set is the intentional allow: it is scoped to another "
      "runtime and must never decide anything here.")
    w("")
    w("| Control | Runtime | What it does | " + " | ".join(_VARIANT_LABEL.get(v, v) for v in variants) + " |")
    w("|---|---|---|" + "---|" * len(variants))
    for sc in sorted(controls, key=lambda s: s["id"]):
        raw = scen_src[sc["id"]]
        cells = []
        for v in variants:
            if v not in sc["variants"]:
                cells.append("n/a")
                continue
            outs = {st["outcome"] for st in sc["variants"][v]["stages"]}
            cells.append(_OUTCOME_LABEL["false_positive"] if "false_positive" in outs
                         else _OUTCOME_LABEL["quiet"])
        w(f"| `{sc['id']}` | {sc['runtime']} | {_cell(raw.get('summary'))} | " + " | ".join(cells) + " |")
    w("")

    w("## Failure modes of the OpenClaw pre-action gate")
    w("")
    w("For OpenClaw, the one control that acts before a command runs is OpenClaw's own exec approval, "
      "which ClawMetry turns on (`openclaw exec-policy preset cautious`) when a require-approval policy "
      "covers exec. These probes run ClawMetry's real gate code with the `openclaw` command stubbed out.")
    w("")
    w("| Id | Situation | Result | Meaning |")
    w("|---|---|---|---|")
    for fm in report["failure_modes"]:
        res = fm.get("result")
        res_txt = ", ".join(f"{k}={json.dumps(v)}" for k, v in res.items()) if res else "not exercised"
        w(f"| {fm['id']} | {_cell(fm['title'])} ({_cell(fm['relates_to'])}) | `{_cell(res_txt)}` | "
          f"{_cell(fm['meaning'])} |")
    w("")
    w("### Not exercised in this tier")
    w("")
    for nx in report["not_exercised"]:
        w(f"- **{nx['id']} {nx['title']}.** {nx['text']}")
    w("")

    w("## Residual gaps")
    w("")
    for g in report["residual_gaps"]:
        where = ", ".join(g.get("stages") or [])
        w(f"- **{g['id']}** ({where}). {g['text']}")
    w("")

    w("## Reproduce")
    w("")
    w("```bash")
    w("python3 -m pytest tests/test_atlas_openclaw_replay.py -q")
    w("python3 scripts/gen_atlas_openclaw_scorecard.py --check")
    w("python3 scripts/gen_atlas_openclaw_scorecard.py --bundle atlas-evidence.json")
    w("python3 scripts/gen_atlas_openclaw_scorecard.py --verify-atlas ATLAS-2026.08.yaml")
    w("```")
    w("")
    w("CI runs the first three. `--verify-atlas` needs MITRE's data file on disk and needs PyYAML, so it "
      "is run by hand when the pins change; it checks every pinned case, step, technique, tactic and "
      "derived mitigation against that file.")
    w("")
    return "\n".join(L)


def verify_atlas(manifest: dict, yaml_path: str) -> list:
    """Every pinned case and step, compared with MITRE's data file. Returns
    a list of mismatch strings (empty means verified)."""
    import yaml  # optional: only this local check needs it
    with open(yaml_path, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return verify_atlas_data(manifest, data)


def verify_atlas_data(manifest: dict, data: dict) -> list:
    """The comparison itself, over an already-parsed ATLAS data file, so it
    is testable without PyYAML or MITRE's file."""
    problems = []
    edition = str((data.get("collection") or {}).get("version") or "")
    if edition != manifest["atlas"]["edition"]:
        problems.append(f"edition {edition!r} != pinned {manifest['atlas']['edition']!r}")
    cs_all = data.get("case-studies") or {}
    techniques = data.get("techniques") or {}
    tactics = data.get("tactics") or {}
    rels = data.get("relationships") or {}
    rel_items = rels.values() if isinstance(rels, dict) else rels
    published = {}
    mitigated_by = {}
    for r in rel_items:
        for e in (r or {}).get("employs") or []:
            published.setdefault(e.get("source"), {})[e.get("step-id")] = (
                e.get("target"), e.get("tactic"))
        for e in (r or {}).get("mitigates") or []:
            mitigated_by.setdefault(e.get("target"), set()).add(e.get("source"))
    mitigations = data.get("mitigations") or {}
    for case in manifest["cases"]:
        src = cs_all.get(case["id"])
        if not src:
            problems.append(f"{case['id']} not in the data file")
            continue
        for key, field in (("name", "name"), ("modified_date", "modified-date")):
            if str(src.get(field)) != str(case[key]):
                problems.append(f"{case['id']} {key}: {src.get(field)!r} != {case[key]!r}")
        steps = published.get(case["id"]) or {}
        if set(steps) != {s["step"] for s in case["steps"]}:
            problems.append(f"{case['id']} step ids differ: {sorted(steps)}")
        for s in case["steps"]:
            tech, tac = steps.get(s["step"], (None, None))
            if tech != s["technique"] or tac != s["tactic"]:
                problems.append(f"{case['id']} {s['step']}: {tech}/{tac} != {s['technique']}/{s['tactic']}")
            if (techniques.get(s["technique"]) or {}).get("name") not in s["technique_name"]:
                problems.append(f"{case['id']} {s['step']}: technique name changed")
            if (tactics.get(s["tactic"]) or {}).get("name") != s["tactic_name"]:
                problems.append(f"{case['id']} {s['step']}: tactic name changed")
        # Mitigations: ATLAS links them to techniques, so the case's list is
        # derived from its step techniques and must match exactly.
        derived = {}
        for s in case["steps"]:
            for mid in mitigated_by.get(s["technique"], ()):
                derived.setdefault(mid, set()).add(s["technique"])
        pinned = {mt["id"]: set(mt["techniques"]) for mt in case.get("mitigations") or []}
        if pinned != derived:
            problems.append(f"{case['id']} mitigations differ: pinned {sorted(pinned)} "
                            f"!= derived {sorted(derived)} (or their techniques differ)")
        for mt in case.get("mitigations") or []:
            if (mitigations.get(mt["id"]) or {}).get("name") != mt["name"]:
                problems.append(f"{case['id']} {mt['id']}: mitigation name changed")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--bundle")
    ap.add_argument("--verify-atlas", dest="verify_atlas")
    args = ap.parse_args()
    replay = load_replay()

    if args.verify_atlas:
        problems = verify_atlas(replay.load_manifest(), args.verify_atlas)
        for p in problems:
            print(f"MISMATCH {p}")
        if problems:
            return 1
        print("every pinned case, procedure step and derived mitigation matches the ATLAS data file")
        return 0

    report = replay.replay_all()
    if args.bundle:
        bundle = replay.evidence_bundle(
            report, generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"))
        with open(args.bundle, "w", encoding="utf-8") as f:
            json.dump(bundle, f, indent=2, sort_keys=True)
            f.write("\n")
        print(f"evidence bundle written to {args.bundle}")
        return 0

    text = render(report)
    if args.check:
        try:
            with open(DOC_PATH, encoding="utf-8") as f:
                current = f.read()
        except FileNotFoundError:
            current = ""
        if current != text:
            print(f"{os.path.relpath(DOC_PATH, REPO_ROOT)} is stale: run "
                  "python3 scripts/gen_atlas_openclaw_scorecard.py", file=sys.stderr)
            return 1
        print("ATLAS OpenClaw scorecard is current")
        return 0
    with open(DOC_PATH, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"wrote {os.path.relpath(DOC_PATH, REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
