# PyInstaller spec for the ClawMetry Windows desktop app (thin shell).
#
# Usage (from repo root, on Windows):
#     pip install -r desktop/requirements-dev.txt
#     pyinstaller --clean --noconfirm desktop/build_windows.spec
#
# Produces `dist/ClawMetry/ClawMetry.exe` — a native Edge WebView2
# desktop app. Code-signing with an EV cert is a separate CI step.
#
# THIN SHELL. Does NOT bundle clawmetry / dashboard / routes /
# helpers. app.py's supervisor creates a runtime venv under
# %LOCALAPPDATA%/ClawMetry/runtime/ on first launch and
# pip-install/upgrades clawmetry into it, so users always run the
# latest PyPI release without redownloading the installer.

# -*- mode: python ; coding: utf-8 -*-
import os
import re
from PyInstaller.utils.hooks import collect_all

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(SPEC), '..'))
ASSETS_SRC = os.path.join(REPO_ROOT, 'desktop', 'assets')

block_cipher = None


# Render VERSIONINFO from dashboard.py __version__ so the .exe advertises
# real CompanyName / ProductName / FileVersion strings in Explorer, Task
# Manager, and the SmartScreen "More info" click-through. Even before a
# code-signing cert lands, this stops the exe from looking anonymous
# (blank publisher, unknown product) — a distinct concern from Authenticode
# trust (see docs/WINDOWS_SIGNING.md). Generated file is a Python literal
# PyInstaller's EXE(version=...) consumes.
def _write_version_info():
    with open(os.path.join(REPO_ROOT, 'dashboard.py'), 'r', encoding='utf-8') as fh:
        m = re.search(r'__version__ = "(.+?)"', fh.read())
    version = m.group(1) if m else '0.0.0'
    parts = (version.split('.') + ['0', '0', '0', '0'])[:4]
    tup = tuple(int(re.sub(r'\D', '', p) or '0') for p in parts)
    out_dir = os.path.join(REPO_ROOT, 'desktop', 'installer')
    os.makedirs(out_dir, exist_ok=True)
    out = os.path.join(out_dir, 'version_info.txt')
    with open(out, 'w', encoding='utf-8') as fh:
        fh.write(f'''# Auto-generated by build_windows.spec — do not edit by hand.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tup!r}, prodvers={tup!r},
    mask=0x3f, flags=0x0, OS=0x40004, fileType=0x1, subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [StringStruct(u'CompanyName', u'InstaLabs LLC'),
         StringStruct(u'FileDescription', u'ClawMetry — observability & governance for AI agents'),
         StringStruct(u'FileVersion', u'{version}'),
         StringStruct(u'InternalName', u'ClawMetry'),
         StringStruct(u'LegalCopyright', u'Copyright (c) InstaLabs LLC. Released under the MIT License.'),
         StringStruct(u'OriginalFilename', u'ClawMetry.exe'),
         StringStruct(u'ProductName', u'ClawMetry'),
         StringStruct(u'ProductVersion', u'{version}')]
      )
    ]),
    VarFileInfo([VarStruct(u'Translation', [0x409, 1200])])
  ]
)
''')
    return out

VERSION_INFO_FILE = _write_version_info()

webview_datas, webview_binaries, webview_hidden = collect_all('webview')

# certifi's cacert.pem must land inside the bundle so onboarding sign-in
# POSTs verify (support 2026-08-12). truststore is preferred at runtime
# (uses Windows Schannel) but Python 3.10+ only.
try:
    certifi_datas, _, certifi_hidden = collect_all('certifi')
except Exception:
    certifi_datas, certifi_hidden = [], []
try:
    _, _, truststore_hidden = collect_all('truststore')
except Exception:
    truststore_hidden = []

brand_datas = [
    (os.path.join(ASSETS_SRC, 'clawmetry-logo-horizontal-darkbg.svg'),
     'desktop/assets'),
    (os.path.join(ASSETS_SRC, 'clawmetry-logo.svg'),
     'desktop/assets'),
    (os.path.join(ASSETS_SRC, 'ClawMetry.ico'),
     'desktop/assets'),
]

extra_hidden = [
    'PIL',
    'webview',
    'webview.platforms.edgechromium',
    'webview.platforms.mshtml',
    'onboarding',  # ships next to app.py; see build_mac.spec for rationale
]

a = Analysis(
    [os.path.join(REPO_ROOT, 'desktop', 'app.py')],
    pathex=[os.path.join(REPO_ROOT, 'desktop')],
    binaries=webview_binaries,
    datas=webview_datas + brand_datas + certifi_datas,
    hiddenimports=(webview_hidden + extra_hidden
                   + certifi_hidden + truststore_hidden),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'clawmetry', 'dashboard', 'routes', 'helpers',
        'flask', 'waitress', 'duckdb', 'cryptography',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='ClawMetry',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=os.path.join(ASSETS_SRC, 'ClawMetry.ico'),
    version=VERSION_INFO_FILE,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='ClawMetry',
)
